import { useState } from 'react'
import { Activity, ArrowDownLeft, ArrowUpRight, Battery, Check, ChevronRight, CircleDot, Clock3, Gauge, LayoutDashboard, LocateFixed, Radio, Send, ShieldCheck, Siren, Terminal, Waypoints, Zap } from 'lucide-react'
import { useGuardian } from './useGuardian'
import type { CommandName } from './types'

const labels: Record<CommandName, string> = { SET_TELEMETRY_RATE: 'Frecuencia de telemetría', REQUEST_CHECK_IN: 'Solicitar check-in', EMERGENCY_MODE: 'Activar emergencia', NORMAL_MODE: 'Restaurar modo normal' }
const time = (value: number) => new Date(value * 1000).toLocaleTimeString('es-MX')

export default function App() {
  const { snapshot: s, connected, history } = useGuardian()
  const [interval, setInterval] = useState('1')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const t = s.telemetry
  const live = connected && s.mqtt_connected && !!t && Date.now() / 1000 - s.received_at < Math.max(5, t.interval_seconds * 3)
  const risk = t?.risk.state ?? 'NORMAL'
  async function send(command: CommandName) {
    setBusy(true); setError('')
    try {
      const response = await fetch('/api/commands', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ command, ...(command === 'SET_TELEMETRY_RATE' ? { interval_seconds: Number(interval) } : {}) }) })
      if (!response.ok) { const data = await response.json(); throw new Error(typeof data.detail === 'string' ? data.detail : 'Comando inválido') }
    } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo enviar') }
    finally { setBusy(false) }
  }
  const metrics = [
    { label: 'Velocidad', value: t?.speed_kmh.toFixed(1), unit: 'km/h', icon: Gauge, note: 'Movimiento del nodo' },
    { label: 'Aceleración', value: t?.acceleration_ms2.toFixed(3), unit: 'm/s²', icon: Zap, note: 'Variación de velocidad' },
    { label: 'Batería', value: t?.battery_percent.toFixed(1), unit: '%', icon: Battery, note: 'Nivel de energía' },
    { label: 'Latencia simulada', value: t?.latency_ms, unit: 'ms', icon: Clock3, note: 'Sensor sintético · no RTT' },
  ]
  const points = history.map((v, i) => `${i * 600 / Math.max(1, history.length - 1)},${150 - v.speed_kmh / 8 * 130}`).join(' ')
  return <div className="shell">
    <aside><a className="brand" href="#"><span className="brand-icon"><ShieldCheck size={25}/></span> GUARDIAN<span className="brand-dot">.</span></a><div className="workspace-label">ESPACIO DE OPERACIONES</div><a className="nav active" href="#overview"><LayoutDashboard size={18}/> Vista general <ChevronRight size={14}/></a><a className="nav" href="#node"><Radio size={18}/> Nodo conectado <span className="count">01</span></a><a className="nav" href="#commands"><Terminal size={18}/> Teleprocesos</a><div className="sidebar-bottom"><div className="mini-shield"><ShieldCheck/></div><strong>Seguridad en movimiento.</strong><p>Telemetría que conecta.<br/>Acciones que acompañan.</p><span className="version">MVP / HACKATHON 24 H</span></div></aside>
    <main id="overview"><header><div className="breadcrumb">Centro de control <ChevronRight size={13}/> Vista general</div><div className="header-status"><span className={`dot ${live ? 'green' : ''}`}/>{live ? 'Sistema conectado' : 'Esperando conexión'}<span className="local-tag">LOCAL</span></div></header>
      <div className="page-title"><div><div className="eyebrow">TELEMETRÍA & TELEPROCESOS</div><h1>GUARDIAN CONTROL CENTER<span>.</span></h1><p>Visibilidad en tiempo real. Acompañamiento en cada trayecto.</p></div><span className="demo-tag"><CircleDot size={14}/> DEMO · NODE-A SIMULADO</span></div>
      <section className="pipeline"><span><Radio size={17}/> NODE-A</span><i>→</i><span className={s.mqtt_connected ? 'pipe-on' : ''}>MQTT</span><i>→</i><span>FastAPI</span><i>→</i><span className={connected ? 'pipe-on' : ''}>WebSocket</span><i>→</i><span><LayoutDashboard size={15}/> Control Center</span><small>FLUJO EN TIEMPO REAL</small></section>
      <div className="section-heading"><h2>Resumen del trayecto</h2><span><span className={`dot ${live ? 'green' : ''}`}/>{live ? `Actualizado ${time(s.received_at)}` : 'Sin telemetría reciente'}</span></div>
      <section className="metrics">{metrics.map(m => <article className="metric" key={m.label}><div className="metric-label">{m.label}<m.icon size={18}/></div><div className="metric-value">{m.value ?? '—'} <small>{m.unit}</small></div><div className="metric-note">{m.note}</div></article>)}</section>
      <div className="content-grid"><section className="panel node-panel" id="node"><div className="panel-title"><h2><Radio size={18}/> Monitor del nodo</h2><span className={`pill ${live ? 'NORMAL' : 'muted'}`}>{live ? 'EN LÍNEA' : 'SIN SEÑAL'}</span></div><div className="node-summary"><div className="node-symbol"><LocateFixed size={30}/></div><div><h3>NODE-A <span>01</span></h3><p>Dispositivo simulado · Trayecto de demostración</p></div><span className="packet">#{t?.sequence ?? '—'} <small>muestra</small></span></div><div className="coordinates"><div><span>LATITUD</span><strong>{t?.latitude.toFixed(6) ?? '—'}°</strong></div><div><span>LONGITUD</span><strong>{t?.longitude.toFixed(6) ?? '—'}°</strong></div><div><span>DESVIACIÓN</span><strong>{t?.route_deviation_m ?? '—'} <small>m</small></strong></div></div><div className="chart-title"><span><Activity size={15}/> Velocidad del trayecto</span><small>Últimas {history.length} muestras · km/h</small></div><div className="chart"><div className="chart-axis"><span>8</span><span>4</span><span>0</span></div><svg viewBox="0 0 600 160" preserveAspectRatio="none" role="img" aria-label="Velocidad de las últimas 60 muestras"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#7da84c" stopOpacity=".2"/><stop offset="1" stopColor="#7da84c" stopOpacity="0"/></linearGradient></defs>{[20,85,150].map(y=><line key={y} x1="0" x2="600" y1={y} y2={y} stroke="#e7eae2" strokeDasharray="4 5"/>)}{history.length > 1 && <><polygon points={`0,160 ${points} 600,160`} fill="url(#fill)"/><polyline points={points} fill="none" stroke="#739d45" strokeWidth="3" vectorEffect="non-scaling-stroke"/></>}</svg>{!t && <span className="chart-empty">Esperando datos de NODE-A…</span>}</div><div className="chart-footer"><span>Adquisición MQTT · QoS 1</span><span>Intervalo aplicado: {t?.interval_seconds ?? '—'} s</span></div></section>
      <section className={`panel risk-panel ${live ? risk : 'muted'}`}><div className="panel-title"><h2><ShieldCheck size={18}/> Evaluación de riesgo</h2><span className="small-label">RULE ENGINE</span></div><div className="risk-icon"><ShieldCheck size={38}/></div><div className="risk-label">{live ? 'ESTADO ACTUAL' : 'ÚLTIMO ESTADO · SIN SEÑAL'}</div><h3 className="risk-state">{t ? risk : 'SIN DATOS'}</h3><p className="risk-subtitle">{live ? 'Evaluación automática de sensores' : 'Inicia el broker, backend y nodo'}</p><div className="risk-scale">{['NORMAL','PRECAUTION','ALERT','CRITICAL'].map(r=><div className={r === risk && live ? 'selected '+r : ''} key={r}><span/><small>{r}</small></div>)}</div><div className="reasons">{t?.risk.reasons.map(reason=><p key={reason}><CircleDot size={13}/>{reason}</p>) ?? <p>Los datos aparecerán al conectar NODE-A.</p>}</div><div className="risk-foot"><Waypoints size={14}/> Reglas transparentes · Sin ML</div></section>
      <section className="panel command-panel" id="commands"><div className="panel-title"><h2><Terminal size={18}/> Teleprocesos</h2><span className="small-label">CONTROL REMOTO</span></div><p className="panel-description">Envía una instrucción. El nodo la ejecuta y confirma con un ACK.</p><div className="rate-control"><label htmlFor="rate">Intervalo de telemetría<small>Menor intervalo = más muestras</small></label><select id="rate" value={interval} onChange={e=>setInterval(e.target.value)}>{[0.5,1,2,5,10].map(n=><option key={n} value={n}>{n} s</option>)}</select><button disabled={!live || busy} onClick={()=>send('SET_TELEMETRY_RATE')}>Aplicar <Send size={14}/></button></div><div className="command-buttons"><button disabled={!live || busy} onClick={()=>send('REQUEST_CHECK_IN')}><Check size={17}/> Solicitar check-in<ArrowUpRight size={15}/></button><button className="emergency" disabled={!live || busy} onClick={()=>send('EMERGENCY_MODE')}><Siren size={17}/> Activar emergencia<ArrowUpRight size={15}/></button><button disabled={!live || busy} onClick={()=>send('NORMAL_MODE')}><ShieldCheck size={17}/> Restaurar modo normal<ArrowUpRight size={15}/></button></div>{error && <p role="alert" className="error">{error}</p>}<div className="command-hint">Check-in automático del simulador. No representa confirmación de una persona.</div></section>
      <section className="panel ack-panel"><div className="panel-title"><h2><ArrowDownLeft size={18}/> Registro de confirmaciones</h2><span className="count">{s.commands.length}</span></div><div className="ack-list" aria-live="polite">{s.commands.length === 0 ? <div className="empty"><Terminal size={28}/><strong>Todo listo para tu primera instrucción</strong><p>Los comandos y sus ACK aparecerán aquí.</p></div> : [...s.commands].reverse().map(c=><article className="ack-row" key={c.command_id}><span className={`ack-dot ${c.status}`}>{c.status === 'EXECUTED' ? <Check size={14}/> : <Clock3 size={14}/>}</span><div><strong>{labels[c.command]}</strong><p>{c.ack?.message ?? (c.status === 'TIMEOUT' ? 'Sin ACK después de 8 s' : 'Esperando ACK de NODE-A…')}</p><code>{c.command_id.slice(0,8)} · {time(c.sent_at)}</code></div><span className={`ack-status ${c.status}`}>{c.status === 'EXECUTED' ? 'ACK ✓' : c.status}</span></article>)}</div></section></div>
      <footer><span><ShieldCheck size={14}/> GUARDIAN · Acompañamiento inteligente</span><span>ENTORNO LOCAL <i>•</i> MVP v0.1</span></footer>
    </main>
  </div>
}
